import type { IconType } from 'react-icons'
import { LuTag, LuStar, LuHeart, LuFlag, LuBookmark, LuPin, LuFlame, LuZap, LuSparkles, LuRocket, LuTarget, LuTrophy, LuCrown, LuGem, LuAward, LuMedal, LuGift, LuBriefcase, LuBuilding, LuBuilding2, LuStore, LuShoppingCart, LuShoppingBag, LuCreditCard, LuWallet, LuDollarSign, LuCoins, LuBanknote, LuReceipt, LuPiggyBank, LuChartBar, LuChartLine, LuChartPie, LuTrendingUp, LuTrendingDown, LuCalculator, LuPercent, LuCode, LuTerminal, LuBug, LuDatabase, LuServer, LuCloud, LuCpu, LuGitBranch, LuGitPullRequest, LuGithub, LuGlobe, LuLink, LuWifi, LuLock, LuShield, LuKey, LuSettings, LuWrench, LuHammer, LuCog, LuPackage, LuBox, LuBoxes, LuLayers, LuBlocks, LuPuzzle, LuPlug, LuBot, LuFileText, LuFile, LuFolder, LuFolderOpen, LuNotebook, LuBookOpen, LuBook, LuLibrary, LuNewspaper, LuPenTool, LuPencil, LuFeather, LuQuote, LuType, LuHeading, LuLanguages, LuSearch, LuScanSearch, LuMail, LuMessageCircle, LuMessageSquare, LuMegaphone, LuBell, LuPhone, LuSend, LuShare2, LuAtSign, LuHash, LuRss, LuRadio, LuMic, LuHeadphones, LuPodcast, LuImage, LuCamera, LuVideo, LuFilm, LuMusic, LuPalette, LuBrush, LuPaintbrush, LuClapperboard, LuTv, LuMonitor, LuSmartphone, LuLaptop, LuTablet, LuWatch, LuGamepad2, LuUsers, LuUser, LuUserPlus, LuContact, LuHandshake, LuSmile, LuBaby, LuGraduationCap, LuSchool, LuCalendar, LuClock, LuTimer, LuHourglass, LuAlarmClock, LuCalendarCheck, LuCircleCheck, LuListTodo, LuClipboardList, LuClipboardCheck, LuInbox, LuArchive, LuTrash2, LuTriangleAlert, LuCircleAlert, LuInfo, LuCircleHelp, LuBan, LuSun, LuMoon, LuCloudRain, LuSnowflake, LuLeaf, LuTreePine, LuFlower2, LuMountain, LuWaves, LuDroplet, LuWind, LuSprout, LuCoffee, LuPizza, LuUtensils, LuApple, LuCake, LuWine, LuBeer, LuCar, LuBus, LuPlane, LuShip, LuBike, LuTruck, LuMapPin, LuMap, LuCompass, LuNavigation, LuHouse, LuHotel, LuTent, LuHeartPulse, LuStethoscope, LuPill, LuActivity, LuDumbbell, LuBrain, LuEye, LuDog, LuCat, LuBird, LuFish, LuPawPrint, LuLightbulb, LuWand, LuMagnet, LuAnchor, LuAtom, LuFlaskConical, LuMicroscope, LuTelescope, LuDna, LuRecycle, LuInfinity } from 'react-icons/lu'
import type { Tag } from '@after-office/shared'

// The icons a tag can have (picked in ui/TagModal.tsx), by group. The stored name is the kebab-case key ("chart-bar");
// the server only checks its shape, so a name dropped from here later just shows the plain tag icon.

export const TAG_ICON_GROUPS: { label: string; icons: [string, IconType][] }[] = [
  { label: 'Popular', icons: [['tag', LuTag], ['star', LuStar], ['heart', LuHeart], ['flag', LuFlag], ['bookmark', LuBookmark], ['pin', LuPin], ['flame', LuFlame], ['zap', LuZap], ['sparkles', LuSparkles], ['rocket', LuRocket], ['target', LuTarget], ['trophy', LuTrophy], ['crown', LuCrown], ['gem', LuGem], ['award', LuAward], ['medal', LuMedal], ['gift', LuGift]] },
  { label: 'Work & money', icons: [['briefcase', LuBriefcase], ['building', LuBuilding], ['building-2', LuBuilding2], ['store', LuStore], ['shopping-cart', LuShoppingCart], ['shopping-bag', LuShoppingBag], ['credit-card', LuCreditCard], ['wallet', LuWallet], ['dollar-sign', LuDollarSign], ['coins', LuCoins], ['banknote', LuBanknote], ['receipt', LuReceipt], ['piggy-bank', LuPiggyBank], ['chart-bar', LuChartBar], ['chart-line', LuChartLine], ['chart-pie', LuChartPie], ['trending-up', LuTrendingUp], ['trending-down', LuTrendingDown], ['calculator', LuCalculator], ['percent', LuPercent]] },
  { label: 'Tech', icons: [['code', LuCode], ['terminal', LuTerminal], ['bug', LuBug], ['database', LuDatabase], ['server', LuServer], ['cloud', LuCloud], ['cpu', LuCpu], ['git-branch', LuGitBranch], ['git-pull-request', LuGitPullRequest], ['github', LuGithub], ['globe', LuGlobe], ['link', LuLink], ['wifi', LuWifi], ['lock', LuLock], ['shield', LuShield], ['key', LuKey], ['settings', LuSettings], ['wrench', LuWrench], ['hammer', LuHammer], ['cog', LuCog], ['package', LuPackage], ['box', LuBox], ['boxes', LuBoxes], ['layers', LuLayers], ['blocks', LuBlocks], ['puzzle', LuPuzzle], ['plug', LuPlug], ['bot', LuBot]] },
  { label: 'Writing', icons: [['file-text', LuFileText], ['file', LuFile], ['folder', LuFolder], ['folder-open', LuFolderOpen], ['notebook', LuNotebook], ['book-open', LuBookOpen], ['book', LuBook], ['library', LuLibrary], ['newspaper', LuNewspaper], ['pen-tool', LuPenTool], ['pencil', LuPencil], ['feather', LuFeather], ['quote', LuQuote], ['type', LuType], ['heading', LuHeading], ['languages', LuLanguages], ['search', LuSearch], ['scan-search', LuScanSearch]] },
  { label: 'Talk', icons: [['mail', LuMail], ['message-circle', LuMessageCircle], ['message-square', LuMessageSquare], ['megaphone', LuMegaphone], ['bell', LuBell], ['phone', LuPhone], ['send', LuSend], ['share-2', LuShare2], ['at-sign', LuAtSign], ['hash', LuHash], ['rss', LuRss], ['radio', LuRadio], ['mic', LuMic], ['headphones', LuHeadphones], ['podcast', LuPodcast]] },
  { label: 'Media', icons: [['image', LuImage], ['camera', LuCamera], ['video', LuVideo], ['film', LuFilm], ['music', LuMusic], ['palette', LuPalette], ['brush', LuBrush], ['paintbrush', LuPaintbrush], ['clapperboard', LuClapperboard], ['tv', LuTv], ['monitor', LuMonitor], ['smartphone', LuSmartphone], ['laptop', LuLaptop], ['tablet', LuTablet], ['watch', LuWatch], ['gamepad-2', LuGamepad2]] },
  { label: 'People', icons: [['users', LuUsers], ['user', LuUser], ['user-plus', LuUserPlus], ['contact', LuContact], ['handshake', LuHandshake], ['smile', LuSmile], ['baby', LuBaby], ['graduation-cap', LuGraduationCap], ['school', LuSchool]] },
  { label: 'Time', icons: [['calendar', LuCalendar], ['clock', LuClock], ['timer', LuTimer], ['hourglass', LuHourglass], ['alarm-clock', LuAlarmClock], ['calendar-check', LuCalendarCheck]] },
  { label: 'Status', icons: [['circle-check', LuCircleCheck], ['list-todo', LuListTodo], ['clipboard-list', LuClipboardList], ['clipboard-check', LuClipboardCheck], ['inbox', LuInbox], ['archive', LuArchive], ['trash-2', LuTrash2], ['triangle-alert', LuTriangleAlert], ['circle-alert', LuCircleAlert], ['info', LuInfo], ['circle-help', LuCircleHelp], ['ban', LuBan]] },
  { label: 'Nature', icons: [['sun', LuSun], ['moon', LuMoon], ['cloud-rain', LuCloudRain], ['snowflake', LuSnowflake], ['leaf', LuLeaf], ['tree-pine', LuTreePine], ['flower-2', LuFlower2], ['mountain', LuMountain], ['waves', LuWaves], ['droplet', LuDroplet], ['wind', LuWind], ['sprout', LuSprout]] },
  { label: 'Food', icons: [['coffee', LuCoffee], ['pizza', LuPizza], ['utensils', LuUtensils], ['apple', LuApple], ['cake', LuCake], ['wine', LuWine], ['beer', LuBeer]] },
  { label: 'Places & travel', icons: [['car', LuCar], ['bus', LuBus], ['plane', LuPlane], ['ship', LuShip], ['bike', LuBike], ['truck', LuTruck], ['map-pin', LuMapPin], ['map', LuMap], ['compass', LuCompass], ['navigation', LuNavigation], ['house', LuHouse], ['hotel', LuHotel], ['tent', LuTent]] },
  { label: 'Health', icons: [['heart-pulse', LuHeartPulse], ['stethoscope', LuStethoscope], ['pill', LuPill], ['activity', LuActivity], ['dumbbell', LuDumbbell], ['brain', LuBrain], ['eye', LuEye]] },
  { label: 'Animals', icons: [['dog', LuDog], ['cat', LuCat], ['bird', LuBird], ['fish', LuFish], ['paw-print', LuPawPrint]] },
  { label: 'Ideas & science', icons: [['lightbulb', LuLightbulb], ['wand', LuWand], ['magnet', LuMagnet], ['anchor', LuAnchor], ['atom', LuAtom], ['flask-conical', LuFlaskConical], ['microscope', LuMicroscope], ['telescope', LuTelescope], ['dna', LuDna], ['recycle', LuRecycle], ['infinity', LuInfinity]] },
]

export const TAG_ICONS: Record<string, IconType> = Object.fromEntries(TAG_ICON_GROUPS.flatMap((g) => g.icons))

/** A tag's icon (the plain tag icon when it has none, or one no longer in the set). */
export function TagIcon({ tag, icon }: { tag?: Pick<Tag, 'icon'>; icon?: string }) {
  const Icon = TAG_ICONS[icon ?? tag?.icon ?? ''] ?? LuTag
  return <Icon />
}
